# conda environments:
#
base                     /home/pgsb/daniel.lang/anaconda3
expression               /home/pgsb/daniel.lang/anaconda3/envs/expression
genie3                   /home/pgsb/daniel.lang/anaconda3/envs/genie3
kallisto                 /home/pgsb/daniel.lang/anaconda3/envs/kallisto
membrane              *  /home/pgsb/daniel.lang/anaconda3/envs/membrane
mro                      /home/pgsb/daniel.lang/anaconda3/envs/mro
orthofinder              /home/pgsb/daniel.lang/anaconda3/envs/orthofinder
othr                     /home/pgsb/daniel.lang/anaconda3/envs/othr
phylo                    /home/pgsb/daniel.lang/anaconda3/envs/phylo
scikit-bio               /home/pgsb/daniel.lang/anaconda3/envs/scikit-bio

